### PR TITLE
chore(core): Removed unnecessary polyfills and libraries.

### PR DESCRIPTION
**Pull request by asial-matagawa**
@frandiox @misterjunio 
This PR removes unnecessary polyfills and libraries.
Any suggestions?

----
Remove:

- ❌ childNodeRemove.js
  - `Element.prototype.remove` is now supported by all major desktop/mobile browsers including iOS 8-10.

- ❌ classList.js@1.1.20150312
  - `Element.prototype.classList` is now supported by all major desktop/mobile browsers (except for IE11).

- ❌ promise-polyfill@6.0.2+mod
  - `Promise` is now supported by all major desktop/mobile browsers (except for IE11).

- ❌ CustomEvent.js
  - `CustomEvent` is now supported by all major desktop/mobile browsers including iOS 8-10 Safari.

- ❌ MutationObserver@0.7.22
  - `MutationObserver` is now supported by all major desktop/mobile browsers including IE11.

- ❌ winstore-jscompat@399fd9f
  -  Currently Onsen UI is not supporting Windows Desktop/Mobile apps and [this library is no longer needed for Windows 10+](https://github.com/Microsoft/winstore-jscompat/tree/399fd9f0b1d7826e0cbc38e8b4618832f12c4b8e#instructions).

----
Keep:

- FastClick@1.0.6+mod
  - To be removed in #2000.

- microevent.js@47cbc14+mod
  - Non-standard. Must be polyfilled.

- setImmediate@1.0.2+mod
  - Non-standard. Supported only in Edge and IE. Must be polyfilled.

### CODE REVIEW

**Comment by frandiox** [comment]
@asial-matagawa Thanks!
Maybe we can include some information in the readme or other file describing which polyfills are included and which ones could be necessary for other browsers?

**Comment by asial-matagawa** [comment]
@frandiox 
>describing which polyfills are included

Actually I removed all the polyfills which Onsen UI has used so far.
The remaining libraries are non-standard ones and non-polyfill ones.

>which ones could be necessary for other browsers

Only IE11 needs polyfills, so I think we can skip this... (unless we start supporting IE11)

**Comment by asial-matagawa** [comment]
I will merge this for now and I will write guide for older browsers later.

**Comment by asial-matagawa** [comment]
It found that this PR broke `ons-navigator` and other components on Safari.

I have investigated this problem and the result is:
- Actually `MutationObserver` polyfill depends on `setImmediate` and polyfills it as needed in [this lines](https://github.com/OnsenUI/OnsenUI/blob/207b4a20bae50d9c4a153020e4e5e3286459ebe7/core/polyfills/MutationObserver%400.7.22/MutationObserver.js#L52-L73).
- But [Onsen UI loads `MutationObserver` polyfill **before** `setImmediate` polyfill](https://github.com/OnsenUI/OnsenUI/blob/207b4a20bae50d9c4a153020e4e5e3286459ebe7/gulpfile.babel.js#L141-L150).
- As a result, `MutationObserver` polyfill adds an `message` event listener and also `setImmediaate` polyfill does the same thing.
- Onsen UI depends on this broken `setImmediate` so far.
- Therefore when I **fixed** `setImmediate`, `ons-navigator` was broken on Safari.

I will restore `MutationObserver` polyfill for now...

**Comment by asial-matagawa** [comment]
Restored in 865f9543e9080b57f99bc7e358287fa956c155c1.

**Pull request merged**
