### PR TITLE
Lazy repeat refactor and auto calculate feature

### PR DESCRIPTION
**Pull request by IliaSky**
The auto calculate feature is turned on only if the user didn't specify the height.

Currently it works only when all items are with the same height, although I think that's the most common use case. Also the code should be faster if we actually know that since otherwise we need to do more calculations when the user scrolls in order for us to know which items to display.

This pull request also enables es6 in angular 1 bindings.

### CODE REVIEW

**Comment by argelius** [comment]
@IliaSky This PR is stale. Can you resolve the conflicts?

**Comment by IliaSky** [comment]
ok

**Comment by IliaSky** [comment]
BTW it's ready for merging :)

**Comment by argelius** [comment]
Thanks @IliaSky !

**Pull request merged**
