### PR TITLE
Show warning when ons-template is not located just under document.body.

### PR DESCRIPTION
**Pull request by asial-matagawa**
@anatoo @frankdiox 

This PR enables `ons-template` to detect nested `ons-template` elements.
Nested `ons-template` elements cause unexpected behaviors like #1801, so I think we should show warning when they are used.

This feature works like:

Is there any problem with this?

### CODE REVIEW

**Comment by frankdiox** [comment]
@asial-matagawa Perhaps we should check that the parent is `document.body`? This way we show the warning if the template is not located in `index.html` under `<body>` tag directly. I think that's the desired behavior.

**Comment by asial-matagawa** [comment]
@frankdiox 
>Perhaps we should check that the parent is document.body?

That is better and I have fixed my implementation according to your suggestion.
The new implementation shows the parent's outerHTML.

Thank you!

**Comment by asial-matagawa** [comment]
@frankdiox 
Maybe completely fixed now.

`this.parentNode` can be `null` even after `connectedCallback` is called due to some CE polyfill-related bug, so I have added `if (this.parentNode)`.

**Comment by frankdiox** [comment]
@asial-matagawa Looks like it still fails in Safari. Can you have a look at it?

**Comment by asial-matagawa** [comment]
@frankdiox 
I think this PR is now safe for merging.
Could you merge this?

**Comment by frankdiox** [comment]
@asial-matagawa Thanks! In any case, as I mentioned the other day, perhaps we should look into native `template` and perhaps deprecate `ons-template`. Looks like @anatoo [also thinks alike](https://twitter.com/anatoo/status/831099657048645632) :)

**Pull request merged**
