### PR TITLE
fix(ons-fab): Page transition animation with fabs.

### PR DESCRIPTION
**Pull request by frandiox**
@asial-matagawa This was fixed some time ago but somehow it was changed again. This fixes again the transitions with FAB/SpeedDial components.

### CODE REVIEW

**Comment by frandiox** [comment]
@asial-matagawa Some more fixes. Looks like the toolbar's zIndex was updated at some point but the fab's wasn't. Also, when popping pages in the navigator, the FAB/SpeedDial disappears suddenly without animation. It should be done asynchronously.

I removed 2 broken tests because I think they don't make sense, the show/hide should be tested in another way.

**Comment by asial-matagawa** [comment]
@frandiox 
Thank you for the changes.
It could be said that `ons-fab` potentially depends on `ons-navigator` and other components...

**Comment by frandiox** [comment]
@asial-matagawa It only depended on `ons-page` and its lifecycle. Anyway, I added an extra `show` that also fixes the animation so it doesn't directly depend on the page anymore for this. Should be fine now.

**Comment by asial-matagawa** [comment]
I see, nice work!

**Pull request merged**
