### PR TITLE
Update Font Awesome to v5.2.0

### PR DESCRIPTION
**Pull request by puku0x**
This PR updates Font Awesome from 4.7.x to 5.2.0. #2501 

```html
<!-- v4 compatible -->
<i class="fa fa-angle-right"></i>
<i class="fa fa-thumbs-up"></i>
<i class="fa fa-twitter"></i>

<!-- v5 style -->
<i class="fas fa-angle-right"></i>
<i class="far fa-thumbs-up"></i>
<i class="fab fa-twitter"></i>
<i class="fab fa-markdown"></i>  <!-- NEW -->

<!-- ons-icon -->
<ons-icon icon="fa-angle-right"></ons-icon>
<ons-icon icon="fa-thumbs-up"></ons-icon>
<ons-icon icon="fa-twitter"></ons-icon>
<ons-icon icon="fa-markdown"></ons-icon>
```

### CODE REVIEW

**Comment by puku0x** [comment]
As mentioned in #2491, Font Awesome's `.fab` class is conflicted with Onsen UI's `.fab`.

Currently, I specify `ons-fab` and `button` considering the use case.

```css
ons-fab, button {
  &.fab {
  }
}
```

This can handle following situations. 

```html
<button class="fab"><i class="fab fa-twitter"></i></button>
<ons-fab>
  <i class="fab fa-twitter"></i>
</ons-fab>
```

**Comment by emccorson** [comment]
Thanks for the PR! In general this all looks good. I noticed the CSS linter is throwing some warnings. Could you fix them before I merge?

```
src/components/fab.css
  94:1   ⚠  Unexpected unknown type selector "ons-fab"                             selector-type-no-unknown   
  94:1   ⚠  Expected empty line before rule                                        rule-empty-line-before     
  94:10  ⚠  Unexpected unknown type selector "ons-speed-dial-item"                 selector-type-no-unknown   
  95:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
  95:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
  95:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
  97:5   ⚠  Expected empty line before rule                                        rule-empty-line-before     
 101:5   ⚠  Expected empty line before rule                                        rule-empty-line-before     
 104:5   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 104:5   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 104:5   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 104:5   ⚠  Expected empty line before rule                                        rule-empty-line-before     
 105:14  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 105:14  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 105:15  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 105:15  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 106:9   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 106:9   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 110:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 110:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 110:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 132:1   ⚠  Unexpected unknown type selector "ons-fab"                             selector-type-no-unknown   
 132:1   ⚠  Unexpected duplicate selector "ons-fab, ons-speed-dial-item, button"   no-duplicate-selectors     
 132:10  ⚠  Unexpected unknown type selector "ons-speed-dial-item"                 selector-type-no-unknown   
 133:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 133:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 133:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 137:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 137:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 137:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 141:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 141:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 141:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 145:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 145:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 145:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 157:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 157:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 157:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:8   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:8   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:9   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:9   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:21  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 158:21  ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 181:1   ⚠  Unexpected unknown type selector "ons-fab"                             selector-type-no-unknown   
 181:1   ⚠  Unexpected duplicate selector "ons-fab, ons-speed-dial-item, button"   no-duplicate-selectors     
 181:10  ⚠  Unexpected unknown type selector "ons-speed-dial-item"                 selector-type-no-unknown   
 182:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 182:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 182:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 188:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 188:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 188:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 192:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 192:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 192:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 198:1   ⚠  Unexpected unknown type selector "ons-fab"                             selector-type-no-unknown   
 199:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 199:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 207:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 207:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 215:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 215:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 223:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 223:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 231:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 231:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 240:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
 240:3   ⚠  Unexpected qualifying type selector                                    selector-no-qualifying-type
```

**Comment by puku0x** [comment]
Specifying element as a selector (e.g. `ons-fab.fab`) makes such warnings.

We can ignore linter by adding some comments.

```css
/* stylelint-disable */
ons-fab, ons-speed-dial-item, button {
  &.fab {
  }
}
/* stylelint-enable */
```

This looks dirty but keeps backward compatibility for now.

**Comment by puku0x** [comment]
I think the best way is to add prefix like `ons-` to all classes.
However, it makes huge breaking changes (there may be a possibility to bump to 3.0.0).

**Comment by emccorson** [comment]
> Specifying element as a selector (e.g. ons-fab.fab) makes such warnings.

Ah, I see. Ok, in that case I will merge this.

> I think the best way is to add prefix like ons- to all classes.
> However, it makes huge breaking changes (there may be a possibility to bump to 3.0.0).

Yes, I think so too. We're already planning to release 2.11.0 in a month or so, but maybe if we include the prefix change as well then we should just go straight to 3.0.0.

**Comment by 4lyn** [comment]
Hi there,
Font Awesome 4.7.x is very different from 5.2.0 (looks very different and has much less choice on free mode)
How is it possible to switch back to 4.7 and still using the latest releases ? Ideally by configuring the theme but I can also patch my own version

**Comment by havezet** [comment]
Is it possible to specify the set to use with ons-icon? e.g.
`<ons-icon icon="fa-circle"></ons-icon>`
will always use the icon from the solid (fas) set. 

If currently not possible then I suggest being able to specify the set in the name; e.g.
`<ons-icon icon="fa-fas-circle"></ons-icon>
<ons-icon icon="fa-far-circle"></ons-icon>`

**Pull request merged**
