### PR TITLE
Animators :: minor cleanup

### PR DESCRIPTION
**Pull request by danjarvis**
iosSlideTransitionAnimator :: remove unused var in _decompose()
overlaySlidingMenuAnimator :: remove unused var in _generateMenuPageStyle()
pushSlidingMenuAnimator :: remove used var in _generateBehindPageStyle()

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @danjarvis !

Will take a look at these changes now.

**Comment by argelius** [comment]
Thanks! Merged.

**Comment by danjarvis** [comment]
Cool.

Have you guys thought about adding `unused: true` to your .jshintrc file? You'll get warnings if you declare vars but don't actually use them.

**Comment by argelius** [comment]
That's a good idea, we will add it :)

**Pull request merged**
