### PR TITLE
chore(ons-navigator): Remove `options.refresh`.

### PR DESCRIPTION
**Pull request by asial-matagawa**
Related issue: #1831

@frandiox 
This PR removes `options.refresh` for `ons-navigator#popPage`.
Is it safe to remove?

### CODE REVIEW

**Comment by frandiox** [comment]
@asial-matagawa Thanks for the PR!
A user suggested adding `navigator.removePage` if we remove `options.refresh`, what I think it could be fine. What do you think about that? It simply calls `pageLoader.unload(pageElement)` or `pageElement._delete()`.

**Comment by asial-matagawa** [comment]
@frandiox 
I think it would be fine if `navigator.removePage` is provided since it is easy for users to find out from onsen.io.
But we have to release 2.3.0 soon, let's postpone it to 2.3.1 and later if we provide `navigator.removePage`.

**Comment by frandiox** [comment]
@asial-matagawa I mean that, if we deprecated `options.refresh`, perhaps we should provide `removePage` in the same release so it is easier for some users to update. I think it is a very easy to implement method. I don't mind if we postpone it but perhaps we should also postpone this PR then?

**Comment by asial-matagawa** [comment]
@frandiox 
Ah, I see.

>I think it is a very easy to implement method.
Actually I don't have enough knowledge to make changes to the core, so I could not estimate the cost. Could you implement `removePage` and related things? I am not sure if we need to make changes to the bindings as well.

**Comment by asial-matagawa** [comment]
@frandiox
I have implemented `removePage` for both of `core` and `angular-onsenui`.
I will merge this.

**Comment by frandiox** [comment]
@asial-matagawa Thanks!

**Pull request merged**
