### PR TITLE
Async methods return promises. Closes #1054

### LINKED ISSUE #1054: Async methods should return promise on all elements.
Async methods(e.g. ons-navigator.pushPage()) on all elements should provide not only callback option but also promise object as return value.

### PR DESCRIPTION
**Pull request by frankdiox**
This closes #1054.

Async methods should return promises that resolve to the new elements. 
This PR allows syntax like: `myNavigator.pushPage(page).then(function(page) { ... } )`.

@argelius Right now this is only for `ons-navigator`. Could you check if this style is OK? I will continue with other components if it's fine.

### CODE REVIEW

**Comment by argelius** [comment]
I think this looks good :)

**Comment by frankdiox** [comment]
@argelius This is done. I have decided the following:

* Navigator methods resolve to new Navigator Page Object.
* Tabbar methods resolve to new page element.
* Splitter-content's "load" resolves to new page element.
* Splitter-side's "load" resolves to new page element.
* Splitter-side open/close/toggle methods resolve to the affected splitter-side element.
* Carousel methods resolve to carousel element.
* Alert methods resolve to alert element.
* Dialog methods resolve to dialog element.
* Popover methods resolve to popover element.
* Modal methods resolve to modal element.

Any suggestion about it?

**Comment by argelius** [comment]
@frankdiox I think these decisions are sound. I will review this later.

There one more thing I want you to do.

I want the `ons.notification.*` methods to a promises as well.

Would be great if you could do 

```javascript
ons.notification.confirm('Are your ready to rumble?')
  .then(
    function() {
      ons.notification.alert('Let's do it!');
    },
    function() {
      ons.notification.alert('Oh well.');
    }
  );
```

**Comment by frankdiox** [comment]
@argelius Yeah that's also implemented. Ons.notification methods return the element itself.

**Comment by argelius** [comment]
@frankdiox Great! :+1:

**Pull request merged**
