### PR TITLE
Fixed some bug.

### PR DESCRIPTION
**Pull request by zack24q**
Fixed error if event is undefined.
Fixed the wrong trigger when <ons-pull-hook> as a direct descendant of <ons-scroller>. issues#707

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @zack24q !

We will take a look at these fixes.

**Comment by frankdiox** [comment]
Thanks @zack24q !
Have you encountered any bug related to undefined value in `event` variable? I believe in that case it should crash in line 470 before reaching your fix. Could you provide a example to reproduce the bug?

**Comment by zack24q** [comment]
Thanks @frankdiox ,my "commented on e884a2b" was wrong, i look the code again and i found the error "Uncaught TypeError: Cannot read property 'gesture' of undefined" is throw by line 76. i look the code and i think this "commented 1f006ab" can fixed the error. Also i am writing an example  to reproduce this bug to you.

**Comment by zack24q** [comment]
please see [codepen](http://codepen.io/zack24qq/pen/aOJjdy), i put ons-list in ons-carousel-item for requirement, sometimes it will throw that error when i scroll down the list.

**Comment by frankdiox** [comment]
@zack24q I am sorry but after hundreds of tries in different browsers I haven't been able to get the error message in your Codepen :(
Can you give me more details about how to reproduce it? Thanks!

**Comment by zack24q** [comment]
@frankdiox my system is window 8 and my browser is chrome 42, and i found my reproduce way.
my network is bad, and i open the Codepen, the result-iframe in Codepen will spend several seconds to load, when it is loaded, i scroll down the list immediately, the error will throw out, and after scrolling several times, there is no new error be thrown.
Another time, when it is loaded for a while, i scroll down the list and there is no new error be thrown.
so i think maybe something is not initialization completed, so user scroll the list will throw that error.
i hope this will help you.

**Comment by frankdiox** [comment]
@zack24q Finally I got the error! I've made another pull request with your changes, but I modified them a little bit. We are also using a specifing commit message format now. Check it out here: #719
Thanks!

**Pull request closed without merging**
