### PR TITLE
Fixed ReferenceError: MutationObserver and CustomEvent are not defined.

### PR DESCRIPTION
**Pull request by ta2xeo**
Android doesn't work in less than OS version 4.4.
MutationObserver.js copied from "https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js"
verification devices
* AQUOS PHONE ZETA SH-01F NTT docomo (OS 4.2.2)
* Galaxy SⅢα SC-03E NTT docomo (OS 4.3)

### CODE REVIEW

**Comment by argelius** [comment]
Hi @ta2xeo !

We've updated the polyfill to a newer version. Can you test the master branch again and see if it works?

**Comment by ta2xeo** [comment]
Thank you for reply.

"CustomEvent" doesn't work.

console log below

```
E/Web Console﹕ Uncaught ReferenceError: CustomEvent is not defined:1109
E/Web Console﹕ Uncaught ReferenceError: CustomEvent is not defined:9358
E/Web Console﹕ Uncaught ReferenceError: CustomEvent is not defined:10349
```

I guess that CustomEvent is not implemented on several old android devices.

Should I define "CustomEvent" in my program?

**Comment by argelius** [comment]
Hi @ta2xeo !

Sorry for the delay. I've added a CustomEvent polyfill now. Does it work for you now?

**Comment by ta2xeo** [comment]
Thanks @argelius !

It works now!
I close this PR.

**Comment by argelius** [comment]
Thanks @ta2xeo !

**Pull request closed without merging**
