### PR TITLE
Missing docs

### PR DESCRIPTION
**Pull request by frankdiox**
I think this is all what was missing.

### CODE REVIEW

**Comment by anatoo** [comment]
@frankdiox 
`registerAnimator()` is not methods for component object.
For instance, `OnsNavigatorElement.regsiterAnimator()` is available, but `$scope.myNavigator.registerAnimator()` is not available on the code below.
```
  <script>
    angular.module('myApp').controller('AppController', function($scope) {
      $scope.myNavigator.registerAnimator(); // ???
    });
  </script>
```
```
<body ng-controller="AppController">    
  <ons-navigator var="myNavigator">
    <ons-page>
      <ons-toolbar>
        <div class="center">Navigator</div>
      </ons-toolbar>
    </ons-page>
  </ons-navigator>  
```
You should move doc comments for these methods.

**Comment by frankdiox** [comment]
@anatoo Oh! I didn't know we changed them in the development branch. I think before it was a normal method. Should I write it in `core/elements` then? Although I think the web page doesn't get docs from there yet.

**Comment by anatoo** [comment]
@frankdiox It's OK to just remove them for now because api-docs generation is not available now on core/elements.

**Comment by frankdiox** [comment]
@anatoo Ok, I reverted the commits and there are no registerAnimators anymore. Thanks!

**Comment by argelius** [comment]
@frankdiox I'm merging this now! Thanks!

**Pull request merged**
