### PR TITLE
Add popToTop() to ons-navigator and expose it to react binding

### PR DESCRIPTION
**Pull request by zabojad**
Hi !
This PR adds a `popToTop()` method to `ons-navigator` and expose it in the `Navigator` react binding.
Please review, comment and merge if OK.
Best.

### CODE REVIEW

**Comment by zabojad** [comment]
@frandiox this is to address https://community.onsen.io/topic/1820/ons-navigator-and-slide-animation-from-right-to-left/4 and in general add a feature common to most projects.

**Comment by frandiox** [comment]
@zabojad Thanks again for another PR! I believe, however, this should be implemented by modifying the behavior of existing methods (through `options` object) instead of creating new methods. Especially considering this one is quite long and will need maintenance. Also, we use `top` nomenclature to refer to the exact opposite concept in `bringPageTop`, so it should be called something like `popHome` or something like that.

In any case, I've made a quick implementation of `resetToPage` with `options.pop` in https://github.com/OnsenUI/OnsenUI/commit/5855145dc93cf1a83a1202fee01255986ad39946 . Can you implement an option like this in React bindings' `resetPageStack` method? I think it should set the new stack + the old topPage, then call `popPage` method instead of `pushPage`.

**Comment by zabojad** [comment]
@frandiox Thank you for your review! I've created a new PR implementing your suggestions: https://github.com/OnsenUI/OnsenUI/pull/2284.

By the way, who is the developper in charge of the react binding at onsen? I've some questions/suggestions regarding their implementation.

**Comment by zabojad** [comment]
BTW, I guess this PR can be closed now...

**Comment by frandiox** [comment]
@zabojad The original creators left long ago. React bindings are basically community driven + me reviewing and refactoring/implementing small features. I think somebody will take care of this from January/February, hopefully :)

**Pull request closed without merging**
