### PR TITLE
insertPage bug. Fixes #691.

### LINKED ISSUE #691: `insertPage` does not show animation when inserting at the top
It should call pushPage() when the page is inserted at the top of the page stack.

### PR DESCRIPTION
**Pull request by frankdiox**
Fixes #691

### CODE REVIEW

**Comment by argelius** [comment]
@frankdiox Looks great! Could you also add this to the Changelog?

**Comment by frankdiox** [comment]
@argelius Changelog modified!

**Comment by argelius** [comment]
Thanks! Will merge now.

**Comment by frankdiox** [comment]
@argelius done!

**Comment by argelius** [comment]
Thanks @frankdiox !

**Pull request merged**
