### PR TITLE
Fixed a bug that caused missing .page__content on Safari.

### PR DESCRIPTION
**Pull request by asial-matagawa**
@frankdiox @anatoo @argelius
IOSSlideNavigatorTransitionAnimator does not work properly on Angular 2 RC.1 + Safari 9.0.3.
It crashes when calling `pushPage` because of absence of `.page__content` element.

Error log is like this:
```
Error: Uncaught (in promise): Error: fail to get ".page__content" element. 
```

I found that on Safari `PageElement#_getContentElement` is called before `_compile`,
so I wrapped the invocation of `this._decompose(enterPage)` with `contentReady`.

Please merge this patch if there is no problem.

### CODE REVIEW

**Comment by anatoo** [comment]
this._decompose(enterPage)だけを遅延させるのではなくて、それ以降のコードも全部遅延させないと壊れそうな気がするんですがそれは大丈夫なんですか?

**Comment by asial-matagawa** [comment]
@anatoo 
[en]
Sorry, I've fixed it.
I mistakenly thought `contentReady` is invoked synchronously.

[ja]
大丈夫じゃなかったです。修正しました。
最初 `IOSSlideNavigatorTransitionAnimator#push` の中身全体を `contentReady` で囲んだら壊れてしまったので `contentReady` で囲む範囲を狭めたのですが、
その際、`contentReady` の第2引数のコールバック関数が同期的に実行されるものと勘違いしていました。

**Comment by anatoo** [comment]
👍

**Comment by argelius** [comment]
Thank you @asial-matagawa !

Can you please also add this fix to the Changelog?

**Comment by asial-matagawa** [comment]
@argelius 
Sure, I will. Thank you for merging!

**Comment by argelius** [comment]
:+1:

**Comment by asial-matagawa** [comment]
@argelius 
Updated! (I thought there is no need to comment on this topic...)
It may cause a conflict, sorry.

I'll do better next time.

**Comment by argelius** [comment]
@asial-matagawa Can you resolve the conflict? I think there is a conflict in CHANGELOG.md so you need to merge latest master branch into your branch.

Please comment here when you are finished so I get a notification :+1:

**Comment by asial-matagawa** [comment]
@argelius
Done. Thank you for information!

**Comment by asial-matagawa** [comment]
@argelius
Done. Thank you for information!

**Comment by argelius** [comment]
@asial-matagawa You removed some lines from the Changelog:

Current changelog on master has these lines:

```
v2.0.0-rc.18
----
 * angular1: Use the `$templateCache` service.
 * ons-splitter: Fix [#1537](https://github.com/OnsenUI/OnsenUI/issues/1537).
 * ons-navigator: Provides animators and allows to extend them.
```

**Comment by asial-matagawa** [comment]
@argelius 
I'm sorry to bother you so often.
It seemed that the master branch in asial-matagawa/OnsenUI  was out-of-date.
I have fixed it.

**Comment by argelius** [comment]
@asial-matagawa No problem! Looks good now :+1:

**Pull request merged**
