### PR TITLE
fixed delayed status bar filling on iOS #897

### PR DESCRIPTION
**Pull request by c58**

### CODE REVIEW

**Comment by argelius** [comment]
@c58 Thanks for the fix! Could you please provide a simple example that reproduces this bug so I can confirm it before merging?

**Comment by c58** [comment]
Sure! 
When switching in menu between page1 and page2 on iOS (reproducable in simulator) inline toolbar and content on page2 does not moved down immediately. See a gif in #897 
```
<ons-sliding-menu menu-page="menu.html" main-page="page1.html" side="left" swipeable="true">
</ons-sliding-menu>

<ons-template name="page1.html">
  <ons-page>No navigator there</ons-page>
</ons-template>

<ons-template name="page2.html">
  <ons-navigator animation="slide" page="page2_list.html">
  </ons-navigator>
</ons-template>

<ons-template name="page2_list.html">
  <ons-page>
    <ons-toolbar></ons-toolbar>
    <ons-toolbar inline></ons-toolbar>
    <ons-list>
      ...many items...
    </ons-list>
  </ons-page>
</ons-template>
```

**Comment by argelius** [comment]
Thanks a lot @c58 ! I will take a look at this.

**Comment by argelius** [comment]
Thanks for this fix @c58 !

Sorry for being late. We had a holiday this week but I'm back now. Will take a look at this tomorrow or early next week.

**Comment by c58** [comment]
No problem, @argelius 
Sorry for my style of commit names and other style problems. If you decide, that my fix is useful, i may recreate commits with your style guides.

**Comment by Hirbod** [comment]
Should be closed as the real problem was only broken tilde selector in iOS 9

**Pull request closed without merging**
