### PR TITLE
Updated angular to 2.4.1.

### PR DESCRIPTION
**Pull request by anatoo**
@asial-matagawa Updated angular to 2.4.1. I will merge this changes if there is no problem.

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@anatoo
Thank you!

I noticed that `fix-1731` branch has not yet been merged.
Could you merge `fix-1731` and then merge this PR?

**Comment by asial-matagawa** [comment]
@anatoo 
Sorry, I said something weird.
For `fix-1731` branch, I would like to ask you to create a new PR.

**Comment by asial-matagawa** [comment]
@anatoo
It seems that Angular 2.4.1 broke something in angular2-onsenui.
Could you fix them?

**Comment by anatoo** [comment]
Fixed.

**Pull request merged**
