### PR TITLE
Reveal, PullHook and Swipe to pop fixes for 2.5.0

### PR DESCRIPTION
**Pull request by frandiox**
@asial-matagawa Due to some changes in animations, the side menus must be hidden for reveal animator, otherwise, they will be partially visible when pushing pages in the navigator. I remember there was a white glitch when using `visibility: hidden` but I couldn't find it on Chrome or Firefox with this `display: none`. Do you think it is fine?

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@frandiox 
Sorry, I am not sure about it now...
I think this kind of changes always need manual testing in real devices.

@misterjunio 
Actually I was told to stop participating in development now.
Could I ask you to make sure that this change does not cause glitches in Android/iOS devices?

**Comment by misterjunio** [comment]
@asial-matagawa sure, will do

**Comment by misterjunio** [comment]
@frandiox @asial-matagawa tested in all devices, no issues found 👍

**Comment by asial-matagawa** [comment]
Thank you! 👍

**Pull request merged**
