### PR TITLE
feat(ons-navigator): make navigator react compatible

### PR DESCRIPTION
**Pull request by philolo1**
@argelius all the tests are passing now, please take a look.

### CODE REVIEW

**Comment by argelius** [comment]
@philolo1 It looks like this branch has diverged from master and there are some conflicts. Can you see if you can merge master into this tomorrow and solve the conflicts?

**Comment by philolo1** [comment]
will take a look thanks!

2016-03-28 22:45 GMT+09:00 Andreas Argelius <notifications@github.com>:

**Comment by philolo1** [comment]
@argelius should be fixed.

**Comment by argelius** [comment]
I'm merging!

**Pull request merged**
