### PR TITLE
feat(vue2): update vue package

### PR DESCRIPTION
**Pull request by Humeira**

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @Humeira !

There are some other things we would also like to change when updating to Vue 2. We will use your commits as base for a bigger PR.

**Comment by Humeira** [comment]
@argelius shall I continue with the migration? I run `vue-migration-helper` and fix where I can.

**Comment by argelius** [comment]
@Humeira Thanks!

If you could help with the migration that would be very appreciated. I will also start doing migration pretty soon but I think we can do it in parallel.

**Comment by Humeira** [comment]
@argelius Maybe add a dedicated `Vue2` branch, instead of merging into `master` directly each time?

Also add a checklist of things to be done. That would be great 👍

**Comment by argelius** [comment]
I've created a new branch from your commits so I will open a new PR. Please make PRs to that branch instead if you make any changes.

https://github.com/OnsenUI/OnsenUI/pull/1674

Next week I will create a list of changes that need to be made for the Vue 2 bindings. If you have any suggestions, please let me know. The current Vue 1 bindings are very simple and I want to create something more powerful for Vue 2.

**Comment by Humeira** [comment]
@argelius okay cool 👍

**Pull request closed without merging**
