### PR TITLE
fix(ons-tabbar): closes #948

### LINKED ISSUE #948: Error when switching tabs
In this demo 
https://github.com/OnsenUI/OnsenUI/blob/master/demo/tabbar/index.html

The following error is thrown sometimes:
```
Uncaught TypeError: Cannot read property '$destroy' of undefined
```

It can be triggered by clicking the tabs furiously.

### PR DESCRIPTION
**Pull request by frankdiox**

### CODE REVIEW

**Comment by argelius** [comment]
@fran: Does this not cause a memory leak?

**Comment by frankdiox** [comment]
@argelius The memory leak was in master before this PR. This fixes another error but does not fix the leak.

**Comment by argelius** [comment]
@frankdiox Ok. Are you working on fixing the memory leak?

If not, please create an issue so we know how to reproduce it.

**Comment by frankdiox** [comment]
@argelius I just reported it. The memory leak is much lower after this fix but there is still something else creating it.

**Pull request merged**
