### PR TITLE
Tag-based release

### PR DESCRIPTION
**Pull request by frankdiox**

### CODE REVIEW

**Comment by frankdiox** [comment]
Release example here: https://github.com/frankdiox/OnsenUI/tree/1.4.6

**Comment by argelius** [comment]
@frankdiox Can you solve conflicts?

**Comment by frankdiox** [comment]
@argelius I think you wanted to modify the release script to adapt it to bash or something, right?

**Comment by argelius** [comment]
@frankdiox I'll check it out now.

**Comment by argelius** [comment]
@frankdiox Works great!

**Pull request merged**
