### PR TITLE
fix(css-components): Fixed list-header

### PR DESCRIPTION
**Pull request by puku0x**
Thank you Onsen UI team !

I found some bug in `css-components/src/components/list.css`.
- `--list-header-background-color` was not defined
- Text color has no opacity
- There is a magic value of `#6c6c6c`

I made a PR, please check it.

image
Left: iOS, Right: Onsen UI v2.2.0 (the current version is not alike iOS)

### CODE REVIEW

**Comment by asial-matagawa** [comment]
Thank you puku0x!

@anatoo
Could you take a look at this?

**Comment by anatoo** [comment]
@puku0x Thanks! I will review this PR.

**Comment by asial-matagawa** [comment]
@anatoo 
FYI: As we decided in the meeting 2 weeks ago, we should not immediately merge patches into `master` branch. We should release patches (and new `CHANGELOG` and `package.json`) by using `production` branch and after that we should merge the patches into `master`.

**Comment by asial-matagawa** [comment]
Also, we should fork the current `production` branch (https://github.com/OnsenUI/OnsenUI/tree/production).
The current `master` branch contains dirty commits which should not be released now.

**Comment by puku0x** [comment]
I found my PR is not enough to solve this problem, therefore I cancel it.
I will make another issue for `ons-list-header`.

**Pull request closed without merging**
