### PR TITLE
fix(ons-page): removed page__content margin

### PR DESCRIPTION
**Pull request by frankdiox**

### CODE REVIEW

**Comment by argelius** [comment]
Hi! I can not find the discussion about this bug anymore. Could you paste an example of the bug that this solves?

If there is no problem I will merge tomorrow.

**Comment by frankdiox** [comment]
@argelius Change tabs here and add the -1px to page__content: http://codepen.io/frankdiox/pen/EVjzag

I don't know if that -1px was fixing something else, I didn't find anything so perhaps it's not necessary for Onsen 2.0.

**Comment by anatoo** [comment]
I added this line(margin-top: -1px) for a display issue on iOS. But I don't remember the details.
It's OK to remove this line if there is no problem on iOS preview.

**Comment by argelius** [comment]
I made some tests on iOS7 and iOS8 without any trouble. Will merge this.

**Pull request merged**
