### PR TITLE
Refine animation of navigator transition.

### PR DESCRIPTION
**Pull request by anatoo**
@masahirotanaka @asial-matagawa I refined default animations of navigator's page transition. Could you review this changes?

### CODE REVIEW

**Comment by masahirotanaka** [comment]
Thanks @anatoo. We should have done this before...

**Comment by asial-matagawa** [comment]
@anatoo
I checked the new animation but looks like some problem exists:
- In iOS, the back arrow appears too fast compared to Settings page in iOS 10.3.
- In Android, the new animation is a bit different compared to Settings page in Android 6.0.

Could you please tell me what you refer to while implementing the new animation?

**Comment by anatoo** [comment]
@asial-matagawa I referred iOS 10.3.2 and Android 6.0.1.  OK, I'm going to adjust again.

**Comment by asial-matagawa** [comment]
@anatoo
Thank you for the changes!
Please feel free to merge this PR.

**Pull request merged**
