### PR TITLE
Added ons-lazy-repeat element.

### PR DESCRIPTION
**Pull request by anatoo**
Implemented ons-lazy-repeat elements.
This changes enable to use ons-lazy-repeat without Angular.

Example:
```
  <script>
    window.onload = setup;
    function setup() {
      document.querySelector('#my-list').delegate = {
        calculateItemHeight: function(i) {
          return 44;
        },
        createItemContent: function(i, template) {
          var dom = template.cloneNode(true);
          dom.innerText = i;
          return dom;
        },
        countItems: function() {
          return 10000000;
        }
      };
    }
  </script>

  <ons-page>
    <ons-toolbar>
      <div class="center">Lazy Repeat</div>
      <div class="right"><ons-toolbar-button onclick="setup()">Setup</ons-toolbar-button></div>
    </ons-toolbar>

    <ons-list>
      <ons-lazy-repeat id="my-list">
        <ons-list-item>
          item
        </ons-list-item>
      </ons-lazy-repeat>
    </ons-list>
  </ons-page>
```
https://github.com/OnsenUI/OnsenUI/blob/dddcbb8babb00dd9fbc43e1001d15dcb606189ea/examples/lazy_repeat_element/index.html

@argelius Please review this spec and code.

### CODE REVIEW

**Comment by argelius** [comment]
This looks great! I will review it now

**Comment by argelius** [comment]
@anatoo The refresh method doesn't seem to work right now. I made a simple example with a list. When I modify the list and run `refresh()` the DOM is not re-rendered.

**Comment by argelius** [comment]
@anatoo Sorry for being late. This works fine now so I will merge.

**Comment by anatoo** [comment]
@argelius Good!

**Pull request merged**
