### PR TITLE
ons platform detect whether device is Android mobile or tablet

### PR DESCRIPTION
**Pull request by JcDenton86**
@argelius is it ok?

### CODE REVIEW

**Comment by frankdiox** [comment]
@JcDenton86 thanks!
However, I think there is some mistake there since Tablet method is exactly the same than Phone method. Check it please :)

**Comment by JcDenton86** [comment]
Hello @frankdiox. They are not the same as the Tablet function returns true if the userAgent has the String Android and not (!) the string Mobile. Check this fiddle: 

http://jsfiddle.net/wcjhzkhz/1/

Is that what you are talking about?

**Comment by frankdiox** [comment]
@JcDenton86 Ohh sorry, I was looking for a more specific way to detect tablets (like reading 'tablet' in the user-agent) and did not see the '!' mark. Looks like this is the only way to detect tablets right now...
It will be reviewed probably on next week :)

**Comment by frankdiox** [comment]
@JcDenton86 I have modified a couple of things and merged your commits in #660
Thanks!

**Comment by JcDenton86** [comment]
Ok @frankdiox. Thanks!

**Pull request closed without merging**
