### PR TITLE
Material Alert Dialog

### PR DESCRIPTION
**Pull request by argelius**

### CODE REVIEW

**Comment by argelius** [comment]
Implemented the design and fixed the `ons.notification.*` methods.

@anatoo
I'm not sure about the classnames:

Right now it's like this:
```
alert-dialog--material-title--one
```

But I think this is better:

```
alert-dialog-title--material--one
```

Or even this:

```
alert-dialog--material__title--one
```

**Comment by anatoo** [comment]
@argelius 
hmm... "alert-dialog--material-title--one" class name looks strange.
Could you fix this naming as you say?

**Comment by argelius** [comment]
@anatoo I changed the class names.

Please merge if there are no problems.

**Comment by anatoo** [comment]
Merged.

**Pull request merged**
