### PR TITLE
First attempt to make ons-navigator react compatible

### PR DESCRIPTION
**Pull request by philolo1**
@argelius Thisi s my first attempt to start integrating react into Onsenui. It creates a component OnsNavigator and OnsPage that handles push/pop and insert right now. It is tricky because of the dom manipulations you have to tell react about. Please have a look also at examples/react.

### CODE REVIEW

**Comment by philolo1** [comment]
i used the package "npm install --dev-save gulp-babel", where should i add this?

**Comment by ggn06awu** [comment]
Is this work expected to work with Onsen 2?

**Comment by philolo1** [comment]
@ggn06awu this is still in the developer state and this commit is only for general discussion how it will/ could look like, but esentially we will support react in OnsenUI 2.0. We will keep you updated!

**Comment by philolo1** [comment]
closing this pull request for now, but have made significant progress and will keep you updated

**Pull request closed without merging**
