### PR TITLE
feat(ngx-onsenui): Add ons-tabbar directive

### PR DESCRIPTION
**Pull request by puku0x**
Related to #2451, this PR proposes `ons-tabbar` directive.

With `swipe` event binding, we can write the callback method as following.

```html
<ons-tabbar swipeable (swipe)="onSwipe($event)">
  <ons-tab></ons-tab>
  <ons-tab></ons-tab>
</ons-tabbar>
```

```ts
onSwipe(event) {
  // Do something with event.index and event.options
}
```

### CODE REVIEW

**Comment by asialgearoid** [comment]
Anything to improve the bindings sounds good to me. Before I merge this, could you update `bindings/angular2/examples/tabbar.ts` to show this way of using it? Do you think there are any useful unit tests that could be added for it? We are currently trying to improve our test coverage.

**Comment by puku0x** [comment]
@asialgearoid OK, I see. I'll try it !

**Comment by puku0x** [comment]
@asialgearoid 
I added a test and update example for tabbar.

**Comment by asialgearoid** [comment]
Great! Thanks for the added example and tests, @puku0x. 😄

**Pull request merged**
