### PR TITLE
Add codepen tags in Angular 2 binding.

### PR DESCRIPTION
**Pull request by anatoo**
@argelius @masahirotanaka Added codepen tags in Angular 2 binding. Merge this changes if there is no problem.

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @anatoo !

**Comment by frankdiox** [comment]
@anatoo @argelius Aren't we using the interactive tutorial for this instead?

**Comment by anatoo** [comment]
@frankdiox Tanaka-san said to use codepen until interactive tutorials are ready.

**Comment by frankdiox** [comment]
@anatoo Yes but it is ready already since you implemented the tutorials. It's even in the webpage: https://onsen.io/v2/docs/angular2/ons-navigator.html

We only need to specify the tutorial in the componens that has a different URL from the vanilla tutorials. For example, [`ons-alert-dialog`](https://onsen.io/v2/docs/angular2/ons-alert-dialog.html) (it shows `ons-dialog` instead). The rest are automatically converted, we do something like --> `hoge.replace('vanilla', 'angular2');`, so if they are under `Reference` category and has the same ID it works.

**Comment by anatoo** [comment]
@frankdiox Oh, I see. I thought that tutorials is not ready because some tutorials have no tutorial contents. 

@argelius Sorry, would you revert this pull-request changes?

**Comment by argelius** [comment]
@anatoo I have reverted this now.

**Comment by anatoo** [comment]
@argelius arigato!

**Pull request merged**
