### PR TITLE
fix(ons-carousel): Fixes #1763.

### LINKED ISSUE #1763: Can't drag the slider of a range component when it is inside of a carousel item.
__Environment__

```
[Core]
    Onsen UI 2.0.4

[Framework]
    React 15.4.1

[Framework binding]
    react-onsenui 1.0.4

[Additional libraries]
    None

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

Can't drag the slider of a range component when it is inside of a carousel item.

__How to reproduce__
https://codepen.io/airamrguez/pen/apbNxz

### PR DESCRIPTION
**Pull request by misterjunio**
@anatoo This is just a simple check in case a drag event is done on a range slider inside carousel as pointed out in #1763. Hope it's good.

### CODE REVIEW

**Comment by anatoo** [comment]
@misterjunio Thanks! But unit-tests failed for your change. Could you fix?

**Comment by misterjunio** [comment]
@anatoo Yep, working on it

**Comment by misterjunio** [comment]
@anatoo @asial-matagawa Should be good now. At @frandiox's suggestion maybe later I'll try to prevent the issue on the `ons-range` side to promote decoupling but for now it works well and I think we can merge.

**Comment by anatoo** [comment]
@misterjunio Good work! Merged.

**Pull request merged**
