### PR TITLE
Replace browserify with Rollup.js

### PR DESCRIPTION
**Pull request by argelius**
This PR replaces browserify with Rollup for bundling.

Some improvements:

* File size is smaller
* The code is cleaner.
* More customizable than browserify bundling.

I also replaced all *.es6 files with *.js since *.es6 is not a standard file extension. Now you don't need to customize your editor to get correct source code highlighting.

Rollup.js adds an UMD to `onsenui.js` so it can easily be consumed with e.g. browserify.

### CODE REVIEW

**Comment by argelius** [comment]
@anatoo What do you think about this?

I think this bundle is a lot better than the one produced by browserify.

**Comment by anatoo** [comment]
It almost looks good to me.

There is only one thing. I think changes of import path is not needed. You should add 'core/src' to module path.
image

**Comment by argelius** [comment]
Thanks @anatoo! I will restore those those imports

**Comment by argelius** [comment]
@anatoo I have restored the import paths. I wrote a simple plugin for Rollup to make it work since it doesn't support module import paths by default.

If there's no problem I will merge these changes.

**Comment by anatoo** [comment]
@argelius It's great! :+1:

**Pull request merged**
