### PR TITLE
chore(dist): modified release script

### PR DESCRIPTION
**Pull request by frankdiox**
Pushes the current version to https://github.com/OnsenUI/OnsenUI-dist
`./dist-release.sh`
or
`./dist-release.sh no-build` (doesn't run `gulp build` before)

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @frankdiox ! Let's use this for the next release. I think we also need to tag old versions in this repo. Can you do that?

Also, could you add some documentation for this to README.md?

**Comment by frankdiox** [comment]
@argelius I uploaded all the old versions after 1.1.0. Before that OnsenUI didn't even use Gulp, so this script won't work.

Where do you want the documentation, in OnsenUI/README.md or OnsenUI-dist/README.md?

**Comment by argelius** [comment]
@frankdiox Please put the documentation in this repo but also write a README.md in the other repo.

**Comment by frankdiox** [comment]
@argelius We need to change now bower and npm to point to OnsenUI-dist. Can you do that?

**Comment by argelius** [comment]
Thanks @frankdiox !

**Pull request merged**
