### PR TITLE
Added ons-popover custom element.

### PR DESCRIPTION
**Pull request by anatoo**
@argelius Merge this changes if there is no problem.

### CODE REVIEW

**Comment by frankdiox** [comment]
This may have conflicts with #752

**Comment by argelius** [comment]
@frankdiox I'm currently merging this so I will resolve the conflicts after that.

**Comment by argelius** [comment]
@anatoo Looks great!

I made some small fixes to the positioning code and also made it possible to change direction dynamically by changing the `direction` attribute.

**Comment by anatoo** [comment]
@argelius Nice work! Thanks!

**Pull request merged**
