### PR TITLE
Vue scroll fix

### PR DESCRIPTION
**Pull request by frandiox**
@asial-matagawa What do you think about mapping `pageElement.scrollTop` to `pageElement._contentElement.scrollTop` (81bf4e9)? I think we should provide a cleaner API for our own bindings even if it is not documented. I don't like too much accessing "private" variables (like `_contentElement`) from the bindings. Other solution would be `pageElement.content.scrollTop`.

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@frandiox 
`pageElement.scrollTop` feels a bit confusing to me since `pageElement` already has its original `scrollTop`.
If it's acceptable, I prefer `pageElement.content.scrollTop`...

**Comment by frandiox** [comment]
@asial-matagawa `pageElement`'s real scrollTop will always be 0, so I don't think it's very interesting. In the past, for example, we were mapping `pageElement`'s style attribute to `.page__background` for the same reason. Do you think it is acceptable or still prefer `pageElement.content`?

**Comment by asial-matagawa** [comment]
@frandiox 
>In the past, for example, we were mapping pageElement's style attribute to .page__background for the same reason.

I see, in that case `pageElement.scrollTop` is better.
Thank you for the PR!

**Comment by frandiox** [comment]
@asial-matagawa I will merge this now. In any case, this is just for internal use so we can change it later.

**Comment by t2thec** [comment]
Hey. Sorry to add to this merge.

I am wanting to add a 'scroll to top' feature (I'm also using the Vue incarnation of Onsen). I can't seem to find any `document.querySelector('#PAGE .SELECTOR').scrollTop` that produces a value greater that `0` that I can then affect.

Any ideas what I am missing? Which element is actually scrolling?

Cheers

**Comment by frandiox** [comment]
@t2thec I think you are looking for `.page__content` selector. In any case, after this was released you can do it directly in the page element (not documented): `pageElement.scrollTop`. Hope it helps!

**Comment by t2thec** [comment]
Thanks @frandiox. Thats is what I had figured.

`document.querySelector('.page__content').scrollTop` just gives me `0` even though I am half way down the page. I'll take another look. I guess I am picking the wrong `.page__content` or something.

Cheers

**Pull request merged**
