### PR TITLE
fix(core): Remove for...of loop.

### PR DESCRIPTION
**Pull request by frandiox**
@asial-matagawa Please have a look at this. I think it should be enough.

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@frandiox 
Thank you!

FYI: Actually [`ons-select.js` also has `for...of`](https://github.com/OnsenUI/OnsenUI/blob/ac6bf2ab0c238a3f036dd2ad2322284b53b6f5a6/core/src/elements/ons-select.js#L230) but it's safe because if the expression after `of` is an array literal it is compiled into a code without `Symbol`.

**Comment by frandiox** [comment]
@asial-matagawa Only with literals? That's interesting...

**Comment by asial-matagawa** [comment]
@frandiox 
This will help: https://www.npmjs.com/package/babel-plugin-transform-es2015-for-of#optimization

**Comment by frandiox** [comment]
@asial-matagawa Yep, that's the same code, I guess we can merge this and release tomorrow :)

**Comment by asial-matagawa** [comment]
♨️

**Pull request merged**
