### PR TITLE
Fix for ons-scroller and ons-carousel. Closes #707

### LINKED ISSUE #707: <ons-pull-hook> as a direct descendant of <ons-scroller> seem not correct
I put "ons-pull-hook" as a direct descendant of "ons-page", it works fine. But when i need to put "ons-pull-hook" in "ons-scroller", it seem not correct. Here is my operation,first i scroll the list to the bottom, so the list's postion is bottom, then i scroll the list up with mouse(not wheel), the “pull-to-refresh” behavior has been triggered. I think the “pull-to-refresh” behavior should be triggered only the list's postion is top. please see my [codepen](http://codepen.io/zack24qq/pen/QbpWEj). Thanks!

### PR DESCRIPTION
**Pull request by frankdiox**
Closes #707

### CODE REVIEW

**Comment by argelius** [comment]
Thanks for the fixes @zack24q ! It's really appreciated :)

@frankdiox Could you please add this to the Changelog and also add @zack24q to the list of contributors?

**Comment by zack24q** [comment]
you are welcome :)

**Comment by frankdiox** [comment]
I think this is finished now!

**Comment by argelius** [comment]
Thanks @frankdiox !

Great job @zack24q ! Merged.

**Pull request merged**
