### PR TITLE
Add Lift Animation to ons-modal element

### PR DESCRIPTION
**Pull request by porchdog**

### CODE REVIEW

**Comment by frandiox** [comment]
@porchdog Thanks for the PR! We'll check it soon :+1:

**Comment by frandiox** [comment]
@anatoo What do you think about this animation? I've fixed the style issues in another branch.

**Comment by anatoo** [comment]
@frandiox It's OK to me.

**Comment by frandiox** [comment]
@porchdog Thanks, this will be merged in #2097

**Pull request closed without merging**
