### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by frankdiox**
@argelius @masahirotanaka Please have a loot at this.

### CODE REVIEW

**Comment by masahirotanaka** [comment]
@frankdiox Thanks. Some suggestions:

1. I think we can only support Windows Phone 10+.
2. Did we still support Android 4.0.2? I thought we support 4.1 and onwards.
3. Can you change the first "Onsen UI" (H1) to "Onsen UI - HTML5 Hybrid Mobile App Framework"
4. The Monaca piece looks good. Can you add the following information:
  To use Monaca CLI:

  ```
  $ [sudo] npm -g install monaca
  $ monaca create helloworld # And choose the starter template
  $ monaca preview # Preview on the browser
  $ monaca debug # Preview on the real device
  ```
5. "How to manually build this project" section can be shorter: It's for high-end users so I think it's enough if we just describe what command to use

**Comment by frankdiox** [comment]
@masahirotanaka I kept the old version for the support and project build. I guess it's better if @argelius checks that part.

**Comment by masahirotanaka** [comment]
Sure. Looks good! :+1:

**Comment by argelius** [comment]
Thanks @frankdiox ! I made some changes and will merge this now.

**Comment by frankdiox** [comment]
@argelius Thansk. Anything to modify about `5. "How to manually build this project" section can be shorter: It's for high-end users so I think it's enough if we just describe what command to use`?

**Pull request merged**
