### PR TITLE
Ons template test

### PR DESCRIPTION
**Pull request by andipavllo**

### CODE REVIEW

**Comment by argelius** [comment]
@andipavllo Please also test the `createdCallback` code. It should test if the content is correctly assigned to `el.template` and that the nodes are removed from the DOM.

**Comment by frankdiox** [comment]
It's actually a bit hard to decide, but I think it should be `fix`, yes :)

**Comment by andipavllo** [comment]
I rebased the commit ;)

**Comment by argelius** [comment]
Thanks @andipavllo !

**Pull request merged**
