### PR TITLE
perf(ons-page): Copy child nodes instead of innerHTML.

### PR DESCRIPTION
**Pull request by argelius**
@anatoo 

Copying innerHTML caused createdCallback to be triggered again for all children.

### CODE REVIEW

**Comment by anatoo** [comment]
@argelius I initially implemented with removeChild and appendChild instead of innerHTML. But it caused angular directive error on "demo/navigator" with iOS and Chrome. Does your implementation work on demo?

**Comment by argelius** [comment]
I'll check it out!

**Comment by anatoo** [comment]
If there is no problem, your implementation is better.

**Comment by argelius** [comment]
It fails on iOS. I will investigate this.

I still think we need to do something different than copying innerHTML since createdCallback will be called far too times for nested elements.

**Comment by argelius** [comment]
@anatoo This implementation works.

**Comment by anatoo** [comment]
Good! Merged it.

**Pull request merged**
