### PR TITLE
fix(ons-splitter): Reveal animation glitch.

### PR DESCRIPTION
**Pull request by frandiox**
@asial-matagawa This should fix the black glitch :smile:

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@frandiox 
Thank you!
I will take a look and merge thsi.

**Comment by asial-matagawa** [comment]
@frandiox 
I have tested it and the black glitch disappeared, but a white glitch sometimes appears on Android Chrome 58.
If you have no Android devices now, I think it would be better to concentrate on some other tasks for now.

**Comment by frandiox** [comment]
@asial-matagawa I found that issue, it's something different. This is related to a `visibility = 'hidden'` after the menu is closed. That is necessary because if there are 2 menus with reveal animation, both of them could be visible under some circumstances when swiping one side...
I'll find a different workaround for that :sweat_smile:

**Comment by asial-matagawa** [comment]
@frandiox 
I see, thank you!

**Comment by frandiox** [comment]
@asial-matagawa I've removed `visibility` property and the glitch should be gone now. Instead, I'm changing the `z-index` property of the splitterSides, so the visible one will be displayed over the hidden one. In order to do that I had to adjust all the splitter `z-index` (content, mask, etc).

I cannot see glitches on Firefox or Chrome 58 anymore :)

**Comment by asial-matagawa** [comment]
@frandiox 
I tested the new revision, and it worked fine!

I will merge this, thank you!

**Pull request merged**
