### PR TITLE
Vue 2 migration

### PR DESCRIPTION
**Pull request by argelius**
Todo:

- [x] Integrate `<ons-tabbar>`. Right now only the CSS for the tabbar is used. We want to use the real `<ons-tabbar>` element in order to get events and animations.
- [x] Integrate `<ons-navigator>`. The way it is currently done is not very nice.
- [x] Integrate dialogs. Dialogs need to render internal content which should be a Vue component.
- [x] Verify that all basic components work well in Vue 2.
- [ ] Write e2e tests.
- [x] Write documentation.

Nice to have:

- [ ] Integration with `vue-router`.

### CODE REVIEW

**Comment by alioygur** [comment]
is there any release date?

**Comment by dannief** [comment]
Does this mean that the current bindings do not work with Vuejs 2.0? Is there anywhere that documents the bindings that are completed and which ones are outstanding?

**Comment by hughsaffar** [comment]
Can't wait to use this!

**Comment by cougarwww** [comment]
Is this ok？

**Comment by asial-matagawa** [comment]
@alioygur @hughsaffar @cougarwww
We have started the development of vue-onsenui again.
I estimate that the work will require 3-6 weeks.

We are planning to discuss the implementation of new `vue-onsenui` on this topic.
Any feedback is welcome!

@dannief 
When we released `vue-onsenui 1.0.0` (preview version), Vue.js was in beta version, so the binding was compatible only to Vue.js 1.
You can find more details in our blog:

Preview! Vue.js support for Onsen UI (2016/08/31)
https://onsen.io/blog/preview-vue-support-onsen-ui/

Onsen UI with Vue 2 will soon be possible! (2016/10/25)
https://onsen.io/blog/onsen-ui-vue-2/

**Comment by auzadventure** [comment]
Looking good. I can't wait for the fix. Let's try to keep the framework as light as possible in the style of vue. I'd be happy to do some documentation work once it comes out. (but my spelling sucks :( )

**Comment by asial-matagawa** [comment]
@auzadventure

>Let's try to keep the framework as light as possible in the style of vue.

Yes, I'd like that. We want to make our binding robust and easy to use.

>I'd be happy to do some documentation work once it comes out.

Thank you! Please be patient until we release `vue-onsenui@2.0.0-alpha.0`...

**Comment by dohomi** [comment]
Will this branch work with https://github.com/nuxt/nuxt.js and SSR? looking forward trying it out soon

**Comment by asial-matagawa** [comment]
@dohomi 
I guess this branch will not work with SSR now.
We hope we can support it but first we should implement some basic functionalities...

**Comment by dohomi** [comment]
@asial-matagawa I think making it SSR ready if you are implementing it now will gain bigger traction of users who would like to use your library. The most important thing is to avoid using the `document` and `window` object and you should be ready to go. The main reason of using Vue2 over Angular or React is the built in SSR support.

**Comment by frankdiox** [comment]
@dohomi Even thought it would be nice, it doesn't really depend on this branch. These are just bindings/wrappers for the core library. I think we would need to change many things in the core to make SSR possible (I haven't seen many examples of Custom Elements + SSR so far). Apart from that, the main focus is still mobile apps rather than mobile websites.

**Comment by dohomi** [comment]
@frankdiox Ok thanks for clarifying it. There are couple of nice component based libraries out like vuetify and elemenFe which are working SSR based. I am validating different libraries at the moment for a future project where SSR is a must

**Comment by Nyarum** [comment]
Again question, maybe do you have some dates to release this binding?

**Comment by frankdiox** [comment]
@Nyarum えっと。。。This was released 2 weeks ago ([alpha.0](https://www.npmjs.com/package/vue-onsenui)). I know it might be a bit confusing since this PR is not merged, but it was released from here (currently solving CSS conflicts in master branch). More info [on the website](https://onsen.io/vue).

**Comment by anatoo** [comment]
I will close this pull-request because I merged `vue2` branch to `master` branch.

**Pull request closed without merging**
