### PR TITLE
feat: react binding page - device back button

### PR DESCRIPTION
**Pull request by francesco-strazzullo**
I Added an onDeviceBackButton to wrap the core page 'onDeviceBackButton'. It's related to the #1850

### CODE REVIEW

**Comment by frandiox** [comment]
@francesco-strazzullo Thanks! A couple of things: I think we don't need 72652b5 anymore, right? Also, according to React docs:

>React doesn't call componentWillReceiveProps with initial props during mounting. It only calls this method if some of component's props may update.

Therefore, I guess it doesn't take the initial value. Am I wrong? We are setting a similar prop in [`componentDidMount` for PullHook](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/PullHook.jsx#L41). I guess that means it is "init only" value, but that's probably fine. Can you have a look at this?

Thanks a lot!

**Comment by francesco-strazzullo** [comment]
@frandiox Yeah you can close the other PR. I think that it's not useful anymore. I think that it's ok to set this value in ```componentDidMount``. I will change it right away.

**Comment by francesco-strazzullo** [comment]
@frandiox it's done!

**Comment by frandiox** [comment]
@francesco-strazzullo Thanks! I'll do this for the other components as well before I forget :)

**Pull request merged**
